server:
  servlet:
    context-path: "/SuperHeroMission" 
spring:
  main:
    banner-mode: "off"
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql : true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
        
logging:
  level:
    org:
      springframework: ERROR
